import type { LearnChapter } from "../types";

export const sqlDatabasesChapters: LearnChapter[] = [
  {
    pathSlug: "sql-databases",
    slug: "sql-intro",
    title: "Introduction to SQL & Relational Databases",
    description: "Tables, rows, keys, and why relational databases remain the default for structured data.",
    level: "beginner",
    minutes: 8,
    content: `## What a relational database stores

A **relational database** organizes data into **tables**—like spreadsheets with strict rules. Each **row** is one record (a user, an order, a blog post). Each **column** is a typed field (\`email\`, \`created_at\`, \`price_cents\`). **SQL** (Structured Query Language) is the standard language to define schemas and query that data.

PostgreSQL, MySQL, SQLite, and SQL Server share core SQL syntax with dialect differences. Learning SQL on one engine transfers to others.

## Tables, schemas, and types

Tables live in **schemas** (PostgreSQL) or databases (MySQL). Columns have types:

- **INTEGER / BIGINT** — Whole numbers
- **TEXT / VARCHAR(n)** — Strings
- **BOOLEAN** — true/false
- **TIMESTAMP WITH TIME ZONE** — Instants in time (prefer timestamptz in Postgres)
- **NUMERIC(p,s)** — Exact decimals for money
- **JSONB** — Semi-structured data (Postgres)

Choose types that reject invalid data at the database layer—not only in application code.

## Primary keys

Every table needs a stable way to identify rows. A **primary key** is unique and not null. Common choices:

- **Surrogate key** — Auto-increment integer or UUID generated by the database
- **Natural key** — Email for users (often avoided as PK because emails change)

UUIDs simplify distributed systems; serial integers are compact and human-friendly in logs.

## Foreign keys and relationships

**Foreign keys** enforce links between tables:

\`\`\`sql
CREATE TABLE posts (
  id         BIGSERIAL PRIMARY KEY,
  author_id  BIGINT NOT NULL REFERENCES users(id),
  title      TEXT NOT NULL
);
\`\`\`

The database refuses to insert \`author_id = 999\` if user 999 does not exist—protecting **referential integrity**.

Relationships:

- **One-to-many** — One user, many posts (\`author_id\` on posts)
- **Many-to-many** — Students and courses via a **join table** \`enrollments(student_id, course_id)\`

## Normalization (brief)

**Normalization** reduces duplication. Store the author's name once in \`users\`, not copied on every post. Reach third normal form for OLTP apps unless you deliberately **denormalize** for read performance with documented tradeoffs.

## ACID guarantees

Transactions provide **Atomicity**, **Consistency**, **Isolation**, **Durability**—covered in a later chapter. For now: the database promises committed work survives crashes and respects constraints.

## SQL vs application code

Use SQL for set operations—filtering millions of rows, joining tables, aggregating sales. Use application code for business orchestration and external APIs. Pushing filters into SQL avoids loading entire tables into memory.

## Tools you will use

- **psql** or GUI clients to run queries
- **Migrations** (Flyway, Drizzle, Prisma) to version schema changes
- **EXPLAIN** to understand query plans

## SQLite vs server databases

**SQLite** embeds in apps and mobile—great for local storage. **PostgreSQL** and **MySQL** run as servers for concurrent web workloads, replication, and advanced types.

## Next steps

You can **SELECT** data, constrain with **WHERE**, combine tables with **JOIN**, and protect money-moving operations with **transactions**. SQL looks declarative—you describe what you want, the optimizer decides how to fetch it. That mindset shift is the core skill.`,
  },
  {
    pathSlug: "sql-databases",
    slug: "select-where",
    title: "SELECT, WHERE & Filtering",
    description: "Retrieve rows, sort results, and express precise filters with SQL.",
    level: "beginner",
    minutes: 10,
    content: `## The basic SELECT

\`SELECT\` reads columns from a table:

\`\`\`sql
SELECT id, title, published_at
FROM posts
WHERE published = true
ORDER BY published_at DESC
LIMIT 10;
\`\`\`

Execution order conceptually: **FROM** → **WHERE** → **SELECT** → **ORDER BY** → **LIMIT**—even though SELECT appears first in syntax.

\`SELECT *\` is fine in exploration; prefer naming columns in application queries to avoid breaking when schema changes.

## WHERE clauses

**WHERE** filters rows before they reach the client:

\`\`\`sql
SELECT * FROM users WHERE email = 'alex@example.com';
SELECT * FROM posts WHERE published_at >= '2024-01-01';
SELECT * FROM products WHERE price_cents BETWEEN 1000 AND 5000;
\`\`\`

Combine conditions:

\`\`\`sql
WHERE status = 'active' AND role IN ('admin', 'editor')
WHERE title ILIKE '%sql%'   -- Postgres case-insensitive
WHERE deleted_at IS NULL
\`\`\`

## NULL semantics

**NULL** means unknown, not zero or empty string. Comparisons with NULL are unknown:

\`\`\`sql
WHERE email IS NOT NULL
WHERE coalesce(nickname, username) = 'alex'
\`\`\`

Use \`IS NULL\` / \`IS NOT NULL\`, not \`= NULL\`.

## Sorting and pagination

\`\`\`sql
ORDER BY created_at DESC, id ASC
LIMIT 20 OFFSET 40;   -- page 3, size 20
\`\`\`

Large **OFFSET** scans skipped rows—slow on big tables. Prefer **keyset pagination**:

\`\`\`sql
WHERE (created_at, id) < ('2024-06-01', 12345)
ORDER BY created_at DESC, id DESC
LIMIT 20;
\`\`\`

## DISTINCT and duplicates

\`SELECT DISTINCT category FROM posts\` removes duplicate categories. Use sparingly—often duplicates signal a missing join condition or need for GROUP BY.

## Expressions and aliases

\`\`\`sql
SELECT
  title,
  length(title) AS title_len,
  published_at::date AS pub_date
FROM posts;
\`\`\`

**Aliases** (\`AS\`) clarify computed columns. Quote identifiers only when necessary (\`"User"\` reserved words).

## INSERT, UPDATE, DELETE basics

\`\`\`sql
INSERT INTO posts (title, author_id) VALUES ('Hello', 1) RETURNING id;

UPDATE posts SET title = 'Updated' WHERE id = 5;

DELETE FROM posts WHERE id = 5;
\`\`\`

Postgres \`RETURNING\` saves a round trip to fetch generated IDs.

Always include a **WHERE** on UPDATE/DELETE unless you intend to touch every row—unscoped updates are operational incidents.

## Parameterized queries

Never concatenate user input:

\`\`\`javascript
// BAD: SQL injection
db.query(\`SELECT * FROM users WHERE email = '\${input}'\`);

// GOOD: parameterized
db.query('SELECT * FROM users WHERE email = $1', [input]);
\`\`\`

ORMs parameterize by default; raw SQL needs discipline.

## EXPLAIN your filters

If a query is slow, run \`EXPLAIN (ANalyze, Buffers)\` in Postgres. Missing indexes on filtered columns often show **Seq Scan** on large tables.

## Practical patterns

- Filter early in WHERE, not in application loops
- Index columns used in WHERE and JOIN
- Keep SELECT lists minimal over the network

SELECT and WHERE are the verbs you will write daily. Precision here—correct NULL handling, pagination, and parameters—prevents bugs and outages.`,
  },
  {
    pathSlug: "sql-databases",
    slug: "joins",
    title: "JOINs Explained",
    description: "Combine tables with INNER, LEFT, and related join patterns.",
    level: "intermediate",
    minutes: 12,
    content: `## Why joins exist

Real data is split across tables. A **JOIN** combines rows from two (or more) tables based on related keys—usually primary key on one side, foreign key on the other.

Without joins you would fetch IDs in one query and loop N queries in application code—the classic **N+1 problem**. One SQL join returns the shape you need.

## INNER JOIN

Returns rows where the join condition matches on **both** sides:

\`\`\`sql
SELECT posts.title, users.name AS author_name
FROM posts
INNER JOIN users ON users.id = posts.author_id;
\`\`\`

Posts without a valid \`author_id\` (if FK not enforced) disappear from results. Orphan posts with missing users are excluded.

## LEFT (OUTER) JOIN

Keeps **all rows from the left table**; matching right columns or NULL:

\`\`\`sql
SELECT users.name, posts.title
FROM users
LEFT JOIN posts ON posts.author_id = users.id;
\`\`\`

Users with zero posts still appear with \`posts.title\` NULL. Use LEFT JOIN when the left entity is primary and related data is optional.

## RIGHT and FULL joins

**RIGHT JOIN** mirrors LEFT with tables swapped—less common; swap tables and use LEFT for readability.

**FULL OUTER JOIN** keeps unmatched rows from both sides—useful for reconciliation reports.

## Multiple joins

\`\`\`sql
SELECT o.id, c.name, p.title
FROM orders o
JOIN customers c ON c.id = o.customer_id
JOIN order_items oi ON oi.order_id = o.id
JOIN products p ON p.id = oi.product_id;
\`\`\`

Mind **cartesian products**: joining without ON duplicates every combination. If row counts explode, check conditions.

## Join vs subquery vs EXISTS

**EXISTS** checks presence efficiently:

\`\`\`sql
SELECT * FROM users u
WHERE EXISTS (
  SELECT 1 FROM posts p WHERE p.author_id = u.id
);
\`\`\`

Often similar plans to INNER JOIN; EXISTS reads well for "users who have at least one post."

**Subqueries** in SELECT:

\`\`\`sql
SELECT u.name, (
  SELECT count(*) FROM posts p WHERE p.author_id = u.id
) AS post_count
FROM users u;
\`\`\`

Convenient for small aggregates; JOIN + GROUP BY may scale better.

## Many-to-many join table

\`\`\`sql
SELECT s.name, c.title
FROM students s
JOIN enrollments e ON e.student_id = s.id
JOIN courses c ON c.id = e.course_id;
\`\`\`

The **enrollments** table holds pairs of foreign keys—sometimes with extra columns (\`enrolled_at\`, \`grade\`).

## Aliases and clarity

Always alias tables (\`posts p\`, \`users u\`) in multi-table queries. Qualify columns (\`p.title\`) to avoid ambiguity.

## Performance notes

Join on **indexed** columns (\`id\`, foreign keys). The planner chooses **Nested Loop**, **Hash Join**, or **Merge Join** based on statistics—run ANALYZE after large loads.

Filter early:

\`\`\`sql
FROM posts p
JOIN users u ON u.id = p.author_id
WHERE p.published_at >= '2024-01-01'
\`\`\`

## Anti-patterns

- Selecting \`SELECT *\` across wide joined tables—pull only needed columns
- Joining on mismatched types (\`text\` vs \`integer\`)—blocks index use
- Using comma joins \`FROM a, b WHERE...\` without explicit JOIN—harder to read

Joins are how relational databases earn their name. Master INNER and LEFT, and most reporting and API queries become single, testable SQL statements.`,
  },
  {
    pathSlug: "sql-databases",
    slug: "aggregates",
    title: "Aggregates & GROUP BY",
    description: "COUNT, SUM, AVG, grouping, and HAVING for summaries and analytics.",
    level: "intermediate",
    minutes: 10,
    content: `## Aggregate functions

**Aggregates** collapse many rows into one summary value:

| Function | Purpose |
|----------|---------|
| COUNT(*) | Row count |
| COUNT(col) | Non-null values in col |
| SUM(col) | Total |
| AVG(col) | Mean |
| MIN / MAX | Extremes |

\`\`\`sql
SELECT count(*) AS total_posts FROM posts;
SELECT sum(amount_cents) AS revenue FROM orders WHERE status = 'paid';
\`\`\`

## GROUP BY

Group rows sharing values, aggregate per group:

\`\`\`sql
SELECT author_id, count(*) AS post_count
FROM posts
GROUP BY author_id;
\`\`\`

Every non-aggregated column in SELECT must appear in GROUP BY (SQL standard). Postgres allows primary-key shortcuts in some cases—do not rely on ambiguity.

## HAVING vs WHERE

**WHERE** filters rows **before** grouping. **HAVING** filters **groups after** aggregation:

\`\`\`sql
SELECT author_id, count(*) AS post_count
FROM posts
WHERE published = true
GROUP BY author_id
HAVING count(*) >= 5;
\`\`\`

You cannot use \`HAVING\` for row-level filters on non-aggregated columns without repeating logic—prefer WHERE for those.

## Multiple dimensions

\`\`\`sql
SELECT date_trunc('month', created_at) AS month,
       status,
       count(*)
FROM orders
GROUP BY 1, 2
ORDER BY 1;
\`\`\`

**date_trunc** (Postgres) buckets timestamps for time-series reports.

## DISTINCT aggregates

\`\`\`sql
SELECT count(DISTINCT user_id) FROM page_views;
\`\`\`

Counts unique visitors, not total page views.

## Window functions (overview)

When you need aggregates **without** collapsing rows, use **window functions**:

\`\`\`sql
SELECT
  title,
  published_at,
  count(*) OVER (PARTITION BY author_id) AS author_total
FROM posts;
\`\`\`

Each row stays visible with a running or partitioned statistic—rankings, moving averages, row numbers.

\`\`\`sql
SELECT title, row_number() OVER (ORDER BY published_at DESC) AS rn
FROM posts;
\`\`\`

## NULL in aggregates

\`COUNT(*)\` counts rows including NULLs in columns; \`COUNT(col)\` skips NULL \`col\`. \`AVG\` ignores NULL inputs.

## Common reporting queries

**Top N per group** (Postgres):

\`\`\`sql
SELECT * FROM (
  SELECT *, row_number() OVER (PARTITION BY category ORDER BY sales DESC) AS rn
  FROM products
) t WHERE rn <= 3;
\`\`\`

**Percentage of total**:

\`\`\`sql
SELECT category,
       sum(amount) * 100.0 / sum(sum(amount)) OVER () AS pct
FROM sales
GROUP BY category;
\`\`\`

## Performance

Aggregates on huge tables scan lots of data—**indexes** on GROUP BY columns help; **materialized views** precompute heavy reports refreshed nightly or on schedule.

## ORM pitfalls

ORMs sometimes fetch all rows and aggregate in Ruby/JavaScript—deadly at scale. Push COUNT and SUM to SQL.

Aggregates turn raw rows into decisions: who posts most, which SKU sells, whether error rates spiked. Pair GROUP BY with clear HAVING filters and window functions when dashboards need detail plus context.`,
  },
  {
    pathSlug: "sql-databases",
    slug: "indexes",
    title: "Indexes & Query Performance",
    description: "How indexes speed lookups and when they hurt writes.",
    level: "intermediate",
    minutes: 11,
    content: `## What an index does

An **index** is a separate data structure (commonly a **B-tree** in Postgres) that lets the database find rows by column value without scanning the entire table. Think of a book index: you jump to pages instead of reading cover to cover.

\`\`\`sql
CREATE INDEX idx_posts_author ON posts(author_id);
CREATE INDEX idx_posts_published_at ON posts(published_at DESC);
\`\`\`

The query planner may use the index for \`WHERE author_id = 5\` or \`ORDER BY published_at DESC LIMIT 10\`.

## When to index

Index columns that appear in:

- **WHERE** equality or range filters
- **JOIN** conditions
- **ORDER BY** on large result sets
- **Foreign keys** (Postgres does not auto-index FKs—add them)

Do not index every column—each index costs **disk** and slows **INSERT/UPDATE/DELETE** because indexes must stay consistent.

## Composite indexes

\`\`\`sql
CREATE INDEX idx_posts_author_date ON posts(author_id, published_at DESC);
\`\`\`

Leftmost prefix rule: efficient for \`WHERE author_id = ?\` and \`WHERE author_id = ? AND published_at > ?\`; less helpful for \`WHERE published_at > ?\` alone.

Put the most selective or equality-filtered column first depending on query mix.

## Unique indexes

\`\`\`sql
CREATE UNIQUE INDEX idx_users_email ON users(lower(email));
\`\`\`

Enforces uniqueness and accelerates lookups. Functional index on \`lower(email)\` supports case-insensitive login.

## Partial indexes

Index a subset of rows:

\`\`\`sql
CREATE INDEX idx_posts_draft ON posts(updated_at) WHERE published = false;
\`\`\`

Smaller index when queries always filter \`published = false\`.

## EXPLAIN and EXPLAIN ANALYZE

\`\`\`sql
EXPLAIN (ANALYZE, BUFFERS)
SELECT * FROM posts WHERE slug = 'hello';
\`\`\`

Look for **Index Scan** vs **Seq Scan**, actual row counts vs estimates, and **Buffers** hit/read. Bad estimates may need **ANALYZE** or adjusted statistics.

## Covering indexes (INCLUDE)

Postgres **INCLUDE** columns store extra payload in the index leaf—index-only scans avoid heap fetches:

\`\`\`sql
CREATE INDEX idx_posts_slug ON posts(slug) INCLUDE (title, published_at);
\`\`\`

## Common problems

- **Missing index** — Seq Scan on millions of rows
- **Wrong type** — Function on column prevents index use unless expression index exists
- **OR conditions** — May defeat single index; consider UNION or restructuring
- **Low selectivity** — Index on boolean \`is_active\` rarely helps

## Vacuum and bloat

Postgres MVCC leaves dead tuples; **VACUUM** (autovacuum) reclaims space. Bloat slows scans—monitor table and index bloat in production.

## Monitoring

Track slow query logs, \`pg_stat_statements\`, and p95 latency after migrations. Adding an index is a schema change—measure before and after.

Indexes are not free magic—they are tradeoffs. Add them for proven slow queries, verify with EXPLAIN, and drop unused indexes discovered by monitoring tools.`,
  },
  {
    pathSlug: "sql-databases",
    slug: "transactions",
    title: "Transactions & Isolation",
    description: "BEGIN, COMMIT, ROLLBACK, and isolation levels for correct concurrent updates.",
    level: "intermediate",
    minutes: 12,
    content: `## Atomicity in action

A **transaction** groups statements into one unit: all succeed (**COMMIT**) or all undo (**ROLLBACK**). Transferring money between accounts must debit and credit together—never one without the other.

\`\`\`sql
BEGIN;
UPDATE accounts SET balance = balance - 100 WHERE id = 1;
UPDATE accounts SET balance = balance + 100 WHERE id = 2;
COMMIT;
\`\`\`

If the second UPDATE fails, ROLLBACK leaves balances unchanged.

Application ORMs expose \`transaction(async () => { ... })\` wrapping the same semantics.

## ACID recap

- **Atomicity** — All or nothing
- **Consistency** — Constraints hold after commit
- **Isolation** — Concurrent transactions behave predictably
- **Durability** — Committed data survives crash (WAL)

## Isolation levels

SQL defines levels trading consistency for concurrency:

| Level | Typical behavior |
|-------|------------------|
| READ COMMITTED | Default in Postgres; sees committed rows only |
| REPEATABLE READ | Same snapshot for transaction duration |
| SERIALIZABLE | Strongest; may raise serialization failures |

**Dirty read** (seeing uncommitted data) is prevented at READ COMMITTED. **Non-repeatable read** and **phantom read** possibilities depend on level.

Postgres REPEATABLE READ and SERIALIZABLE use snapshot isolation; SERIALIZABLE detects conflicts and may abort with \`40001\`—retry the transaction.

## Row-level locking

\`\`\`sql
SELECT * FROM accounts WHERE id = 1 FOR UPDATE;
\`\`\`

Locks the row until transaction ends—use in "read balance → compute → write" flows to prevent lost updates.

**SKIP LOCKED** helps job queues: workers grab unlocked rows without blocking.

## Deadlocks

Two transactions locking rows in opposite order can **deadlock**—Postgres aborts one; apps should retry. Lock resources in consistent order globally.

## Optimistic concurrency

Add a **version** column:

\`\`\`sql
UPDATE posts
SET title = $1, version = version + 1
WHERE id = $2 AND version = $3;
\`\`\`

If zero rows updated, someone else changed the row—merge or show conflict UI instead of silent overwrite.

## Savepoints

\`\`\`sql
BEGIN;
INSERT INTO logs ...;
SAVEPOINT sp1;
-- risky operation
ROLLBACK TO sp1;
COMMIT;
\`\`\`

Partial rollback inside a transaction.

## What belongs in a transaction

- Multi-step financial or inventory updates
- Deleting parent and children together
- Publishing atomically (post + tags + search index enqueue)

Avoid long transactions holding locks while calling external APIs—keep transactions short.

## Read-only transactions

\`\`\`sql
BEGIN READ ONLY;
-- reporting queries
COMMIT;
\`\`\`

Hints optimization on replicas.

## Testing concurrency

Integration tests with parallel connections expose race bugs. Simulate two checkout flows buying the last item—only one should succeed.

Transactions turn "a bunch of SQL" into promises your application can rely on. Choose isolation consciously, lock when needed, retry on serialization failure, and never leave transactions open across network calls.`,
  },
  {
    pathSlug: "sql-databases",
    slug: "postgres-tips",
    title: "PostgreSQL Tips & Patterns",
    description: "JSONB, UPSERT, extensions, and Postgres-specific features worth knowing.",
    level: "intermediate",
    minutes: 11,
    content: `## Why PostgreSQL

**PostgreSQL** is a full-featured open-source RDBMS: strict SQL compliance, rich types, extensions, and strong concurrency (MVCC). It powers many production APIs and analytics pipelines. Tips here assume Postgres 14+ unless noted.

## JSONB for flexible fields

Store semi-structured metadata without schema churn:

\`\`\`sql
ALTER TABLE products ADD COLUMN attrs JSONB NOT NULL DEFAULT '{}';
SELECT * FROM products WHERE attrs @> '{"color":"red"}';
CREATE INDEX idx_products_attrs ON products USING gin(attrs);
\`\`\`

**JSONB** is binary, indexable; prefer it over JSON text type. Validate shape in application or with **CHECK** constraints and triggers.

## UPSERT (ON CONFLICT)

Insert or update in one statement:

\`\`\`sql
INSERT INTO settings (user_id, key, value)
VALUES (1, 'theme', 'dark')
ON CONFLICT (user_id, key)
DO UPDATE SET value = EXCLUDED.value, updated_at = now();
\`\`\`

Requires a UNIQUE constraint on \`(user_id, key)\`. \`EXCLUDED\` refers to the proposed insert row.

## RETURNING clause

Avoid extra SELECT after INSERT/UPDATE:

\`\`\`sql
INSERT INTO posts (title) VALUES ('Hi') RETURNING id, created_at;
DELETE FROM sessions WHERE expires_at < now() RETURNING id;
\`\`\`

## Arrays and enums

Postgres supports **array** columns and **ENUM** types for controlled vocabularies—use enums sparingly ( altering enums is awkward); lookup tables or text + CHECK are often simpler.

## Common extensions

\`\`\`sql
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS pg_trgm;  -- fuzzy text search
CREATE EXTENSION IF NOT EXISTS citext;   -- case-insensitive text
\`\`\`

Enable only what you need; document in migrations.

## Full-text search

\`\`\`sql
ALTER TABLE articles ADD COLUMN search tsvector
  GENERATED ALWAYS AS (to_tsvector('english', coalesce(title,'') || ' ' || coalesce(body,''))) STORED;
CREATE INDEX idx_articles_search ON articles USING gin(search);
SELECT * FROM articles WHERE search @@ plainto_tsquery('english', 'postgres indexes');
\`\`\`

Good enough for many apps before Elasticsearch.

## Connection pooling

Postgres connections are processes—expensive at thousands of clients. Use **PgBouncer** or pooler in managed services; keep transactions short when pooling in transaction mode.

## Sequences and identity

\`GENERATED BY DEFAULT AS IDENTITY\` is modern replacement for serial. For distributed IDs consider **uuid** v4 or v7 (time-sortable).

## Listen/notify and logical replication

\`LISTEN channel\` / \`NOTIFY\` for lightweight pub/sub inside Postgres. Logical replication streams changes to analytics DBs—operational concern for DBAs.

## Maintenance commands

- \`VACUUM (ANALYZE)\` — statistics and dead tuples
- \`REINDEX CONCURRENTLY\` — fix bloated indexes online
- Monitor replication lag on read replicas

## Security

- Least-privilege roles: app user without SUPERUSER
- \`ROW LEVEL SECURITY\` for multi-tenant isolation
- Prefer \`sslmode=require\` for remote connections

Postgres rewards learning beyond portable SQL—JSONB, UPSERT, and GIN indexes solve real product problems without jumping to a document store on day one.`,
  },
  {
    pathSlug: "sql-databases",
    slug: "backup-restore",
    title: "Backup & Restore",
    description: "Logical dumps, physical backups, and recovery practices that prevent data loss.",
    level: "intermediate",
    minutes: 10,
    content: `## Why backups matter

Hardware fails, migrations go wrong, ransomware encrypts disks, and someone runs DELETE without WHERE. **Backups** are the difference between a brief incident and a company-ending event. A backup you never tested restoring is wishful thinking.

Define **RPO** (how much data you can lose) and **RTO** (how fast you must be back). Daily dumps may mean 24 hours RPO; continuous archiving shrinks that.

## Logical backups (pg_dump)

**pg_dump** exports SQL or custom format for a database:

\`\`\`bash
pg_dump -Fc -f backup.dump "$DATABASE_URL"
pg_dump --schema-only -f schema.sql mydb
\`\`\`

Restore:

\`\`\`bash
pg_restore -d mydb --clean --if-exists backup.dump
# or plain SQL:
psql mydb < backup.sql
\`\`\`

Logical dumps are portable across versions (with caveats), good for selective restore of one database, and easy to store in S3 with encryption.

## Physical backups

**File-system** or **volume snapshots** copy data directory bytes—fast for huge databases. **pg_basebackup** creates a binary base for point-in-time recovery (PITR) with WAL archiving.

Managed providers (RDS, Supabase, Neon) automate snapshots—still verify you can restore to a new instance.

## Point-in-time recovery

Archive **WAL** (write-ahead log) segments continuously. After restoring a base backup, replay WAL to a timestamp before the accidental DROP:

\`\`\`bash
recovery_target_time = '2024-06-15 14:32:00 UTC'
\`\`\`

Requires \`archive_mode = on\` and reliable WAL storage.

## Backup schedule habits

- Automated daily full logical or snapshot
- WAL continuous if RPO < 1 day
- Off-site and **encrypted** storage (SSE-KMS, client-side for sensitive data)
- Retention policy (30 daily, 12 monthly)
- **Test restore** monthly to a staging cluster

## What to exclude

Huge ephemeral caches or reproducible search indexes need not bloat backups—document what is source of truth.

## Application-consistent backups

Quiesce writes or use snapshots coordinated with the database so files are not mid-transaction. pg_dump uses a consistent snapshot via MVCC—safe for live dumps without stopping traffic.

## Secrets and compliance

Backup files contain everything—PII, password hashes, API keys in settings tables. Encrypt at rest, restrict IAM, never commit dumps to git.

## Disaster runbook

Document steps: who gets paged, how to provision blank DB, restore command, DNS cutover, verification queries (\`SELECT count(*)\`, checksum samples), and communication template.

## SQLite and small projects

Copy the \`.db\` file while application paused, or use \`.backup\` command—simple but easy to forget.

## Monitoring

Alert on backup job failure, age of latest snapshot, and WAL archive gaps.

Backups are insurance. Automate them, encrypt them, test restores before you need them, and sleep better during deploys.`,
  },
];
